version: '3'

services: 
  web:
    container_name: utb_api
    restart: always
    build: .
    ports:
      - 8080:80
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_PROFILE: "Production"
      UTB_PG_HOST: utb_postgres
      UTB_PG_PORT: ${UTB_PG_PORT}
      UTB_PG_DB: ${UTB_PG_DB}
      UTB_PG_USER: ${UTB_PG_USER}
      UTB_PG_PASS: ${UTB_PG_PASS}
    depends_on: 
      - 'postgres'
      
  postgres:
    container_name: utb_postgres
    image: postgres:latest
    restart: always
    environment: 
      - "POSTGRES_USER=${UTB_PG_USER}"
      - "POSTGRES_PASSWORD=${UTB_PG_PASS}"
      - "POSTGRES_DB=${UTB_PG_DB}"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - ${UTB_PG_PORT}:5432
