version: '3'

services: 
  web:
    container_name: utb_api
    restart: always
    build: .
    ports:
      - 8080:80
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_PROFILE: "Production"
      ConnectionStrings__PGSQL_DEV: "Host=utb_postgres;Port=5432;Database=${UTB_POSTGRES_DB};Username=${UTB_POSTGRES_USER};Password=${UTB_POSTGRES_PASSWORD}"
    depends_on: 
      - 'postgres'
      
  postgres:
    container_name: utb_postgres
    image: postgres:latest
    restart: always
    environment: 
      - "POSTGRES_USER=${UTB_POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${UTB_POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${UTB_POSTGRES_DB}"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - 21992:5432
