version: '3'

services: 
    postgres:
        container_name: utb_postgres
        image: postgres:latest
        restart: always
        environment: 
            - "POSTGRES_USER=${UTB_POSTGRES_USER}"
            - "POSTGRES_PASSWORD=${UTB_POSTGRES_PASSWORD}"
            - "POSTGRES_DB=${UTB_POSTGRES_DB}"
            - "PGDATA=/var/lib/postgresql/data/pgdata"
        volumes: 
            - ./database:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
