version: '3'

services: 
  web:
    container_name: utb_api
    build: .
    ports:
      - 8080:80
      - 8081:443
    environment: 
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081" 
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__PGSQL_DEV: "Host=utb_postgres;Port=5432;Database=${UTB_POSTGRES_DB};Username=${UTB_POSTGRES_USER};Password=${UTB_POSTGRES_PASSWORD}"
    volumes: 
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets
      - ~/.aspnet/https:/root/.aspnet/https
    depends_on: 
      - 'postgres'
      
  postgres:
    container_name: utb_postgres
    image: postgres:latest
    restart: always
    environment: 
      - "POSTGRES_USER=${UTB_POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${UTB_POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${UTB_POSTGRES_DB}"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
