version: '3'

services: 
  web:
    container_name: utb_api
    restart: always
    build: 
      context: .
      dockerfile: API.Dockerfile
    image: iboutsikas/underthebay-api
    ports:
      - ${UTB_API_PORT}:80
    environment: 
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_PROFILE: "Production"
      UTB_PG_HOST: ${UTB_PG_HOST}
      UTB_PG_PORT: ${UTB_PG_PORT}
      UTB_PG_DB: ${UTB_PG_DB}
      UTB_PG_USER: ${UTB_PG_USER}
      UTB_PG_PASS: ${UTB_PG_PASS}
    depends_on: 
      - 'postgres'

  console:
    container_name: utb_console
    restart: always
    build: 
      context: .
      dockerfile: Console.Dockerfile
    image: iboutsikas/underthebay-console
    environment:
      UTB_PG_HOST: ${UTB_PG_HOST}
      UTB_PG_PORT: ${UTB_PG_PORT}
      UTB_PG_DB: ${UTB_PG_DB}
      UTB_PG_USER: ${UTB_PG_USER}
      UTB_PG_PASS: ${UTB_PG_PASS}
    depends_on: 
      - 'postgres'
      
  postgres:
    container_name: utb_postgres
    image: postgres:latest
    restart: always
    environment: 
      - "POSTGRES_USER=${UTB_PG_USER}"
      - "POSTGRES_PASSWORD=${UTB_PG_PASS}"
      - "POSTGRES_DB=${UTB_PG_DB}"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes: 
      - utb_postgres_vm:/var/lib/postgresql/data/pgdata
    ports:
      - ${UTB_PG_PORT}:5432

volumes:
  utb_postgres_vm
