// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UTB.Data;

#nullable disable

namespace UTB.Data.Migrations
{
    [DbContext(typeof(UtbContext))]
    partial class UtbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UTB.Data.Models.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("BlueGreenAlgae")
                        .HasColumnType("real");

                    b.Property<float>("Chlorophyll")
                        .HasColumnType("real");

                    b.Property<float>("DissolvedOxygen")
                        .HasColumnType("real");

                    b.Property<float>("DissolvedOxygenSaturation")
                        .HasColumnType("real");

                    b.Property<float>("Salinity")
                        .HasColumnType("real");

                    b.Property<Instant>("SampleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("SampleDepth")
                        .HasColumnType("real");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<float>("Turbidity")
                        .HasColumnType("real");

                    b.Property<float>("WaterTemperature")
                        .HasColumnType("real");

                    b.Property<float>("pH")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("UTB.Data.Models.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThreeLetterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("UTB.Data.Models.Sample", b =>
                {
                    b.HasOne("UTB.Data.Models.Station", "Station")
                        .WithMany("Samples")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("UTB.Data.Models.Station", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
