apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: utb-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /index.html
    port: 80